import utils from '../../../helpers/utils';

const requestQuote = () => {
  let domString = '';
  domString += '<form>';
  domString += '<div class="form-group">';
  domString += '    <label for="first-name">First Name</label>';
  domString += '  <input type="text" class="form-control" id="first-name">';
  domString += '</div>';
  domString += '<div class="form-group">';
  domString += '    <label for="last-name">Last Name</label>';
  domString += '  <input type="text" class="form-control" id="last-name">';
  domString += '</div>';
  domString += '<div class="form-group">';
  domString += '<div class="form-group">';
  domString += '<label for="exampleInputEmail1">Email address</label>';
  domString += '<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">';
  domString += '<small id="emailHelp" class="form-text text-muted">We will never share your email with anyone else.</small>';
  domString += '</div>';
  domString += '<div class="form-group">';
  domString += '    <label for=vehicle-year">Vehicle Year</label>';
  domString += '  <input type="text" class="form-control" id="vehicle-year">';
  domString += '</div>';
  domString += '<div class="form-group">';
  domString += '    <label for=vehicle-make">Vehicle Make</label>';
  domString += '  <input type="text" class="form-control" id="vehicle-make">';
  domString += '</div>';
  domString += '<div class="form-group">';
  domString += '    <label for=vehicle-model">Vehicle Model</label>';
  domString += '  <input type="text" class="form-control" id="vehicle-model">';
  domString += '</div>';
  domString += '<div class="form-group form-check">';
  domString += '<input type="checkbox" class="form-check-input" id="exampleCheck1">';
  domString += '<label class="form-check-label" for="exampleCheck1">Please check box if your car has tint that needs to be removed</label>';
  domString += '</div>';
  domString += '<button type="submit" class="btn btn-primary">Submit</button>';
  domString += '</form>';
  utils.printToDom('quote', domString);
};

export default { requestQuote };
